#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-jquery-ui
Version  : 1.11.0.1
Release  : 10
URL      : https://pypi.python.org/packages/source/X/XStatic-jquery-ui/XStatic-jquery-ui-1.11.0.1.tar.gz
Source0  : https://pypi.python.org/packages/source/X/XStatic-jquery-ui/XStatic-jquery-ui-1.11.0.1.tar.gz
Summary  : jquery-ui 1.11.0 (XStatic packaging standard)
Group    : Development/Tools
License  : MIT
Requires: XStatic-jquery-ui-python
BuildRequires : python-dev
BuildRequires : setuptools

%description
XStatic-jquery-ui
-----------------
jquery-ui javascript library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-jquery-ui package.
Group: Default

%description python
python components for the XStatic-jquery-ui package.


%prep
%setup -q -n XStatic-jquery-ui-1.11.0.1

%build
%{__python} setup.py build

%install
rm -rf %{buildroot}
%{__python} setup.py install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
